receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 30s
        static_configs:
        - targets: ['0.0.0.0:443']
processors:
  attributes/betterstack:
    actions:
      - key: better_stack_source_token
        value: nSuyuSaJhKLBjwxKe1Sr3hLN
        action: insert
  batch:

exporters:
  otlp/betterstack:
    endpoint: "https://in-otel.logs.betterstack.com:443"
  prometheusremotewrite/betterstack:
    endpoint: "https://in-otel.logs.betterstack.com/metrics"
service:
  pipelines:
    metrics/betterstack:
      receivers: [otlp, prometheus] # You can add more metrics receivers here
      processors: [batch, attributes/betterstack]
      exporters: [prometheusremotewrite/betterstack]
    logs/betterstack:
      receivers: [otlp] # You can add more logs receivers here
      processors: [batch, attributes/betterstack]
      exporters: [otlp/betterstack]
