receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  attributes/betterstack:
    actions:
      - key: better_stack_source_token
        value: nSuyuSaJhKLBjwxKe1Sr3hLN
        action: insert
  batch:
  # NOTE: this is an example of extensions you can add to
  #   the collector deployment
  # memory_limiter:
  #   # 80% of maximum memory up to 2G
  #   limit_mib: 400
  #   # 25% of limit up to 2G
  #   spike_limit_mib: 300
  #   check_interval: 5s
extensions:
  health_check:
  # NOTE: this is an example of extensions you can add to
  #   the collector deployment
  # memory_ballast:
  #   # Memory Ballast size should be max 1/3 to 1/2 of memory.
  #   size_mib: 200
exporters:
  otlp/betterstack:
    endpoint: "https://in-otel.logs.betterstack.com:443"
  prometheusremotewrite/betterstack:
    endpoint: "https://in-otel.logs.betterstack.com/metrics"
  prometheusremotewrite:
    endpoint: ${env:OTEL_PROM_URL}/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels
service:
  extensions: [health_check]
  pipelines:
    metrics/1:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]
    metrics/betterstack:
      receivers: [otlp, prometheus] # You can add more metrics receivers here
      processors: [batch, attributes/betterstack]
      exporters: [prometheusremotewrite/betterstack]
    logs/betterstack:
      receivers: [otlp] # You can add more logs receivers here
      processors: [batch, attributes/betterstack]
      exporters: [otlp/betterstack]
